### ISSUE TITLE
Assertion failed: ipc_frame.header.flags

### ISSUE THREAD

**Issue by teeramusic** [Submersible/node-python-bridge#3] opened 2016-11-26 08:36 UTC
trying to run the example in the readme, I get this...

Assertion failed: ipc_frame.header.flags <= (UV_IPC_TCP_SERVER | UV_IPC_RAW_DATA | UV_IPC_TCP_CONNECTION), file src\win\pipe.c, line 1591

**Comment by munro** [comment] 2016-12-06 21:10
I don't have a Windows machine to debug the issue, but if you figure out a fix, I'll gladly accept a PR!

Unfortunately travis-ci doesn't support Windows, but it looks like there is another free service for Windows automated testing. [1] 😮

[1] https://www.appveyor.com/

**Comment by munro** [comment] 2017-02-28 01:18
Hey @teeramusic I got the error to reproduce with Appveyor [1], would you have any free time to help create fix for this?  The feedback loop of developing through a CI is very tedious 😄 

https://github.com/Submersible/node-python-bridge/tree/windows_support

**Closed** 2017-03-03 03:43 UTC
